import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AosInit from "@/components/AosInit";
import { GlobalSchemas } from "@/components/Schemas";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Our People | Our Services ",
    description: "Generated by Gosirat",
    icons: {
        icon: "/favicon.ico?v=1",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${inter.variable} font-sans h-full antialiased`}
        >
            <head>
                <link rel="icon" href="/favicon.ico?v=1" />
                <link rel="shortcut icon" href="/favicon.ico?v=1" />
                <link rel="apple-touch-icon" href="/favicon.ico?v=1" />
            </head>
            <body className="min-h-full flex flex-col overflow-x-hidden" suppressHydrationWarning>
                <GlobalSchemas />
                <AosInit />
                <Header />
                <main className="flex-1 flex flex-col">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
